/*
You are given two strings s and t.
String t is generated by random shuffling string s 
and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
*/

const findDiff = (s, t) => {
  //initialize an empty cache
  const cache = {};
  //iterate through s and add the letter to the cache with value of +1
  for (let i = 0; i < s.length; i++) {
    if (cache.hasOwnProperty(s[i])) {
      cache[s[i]] += 1
    }
    else cache[s[i]] = 1
  }
  //iterate through t
    //if character is not found in cache, return the character
    //else if the character is present and value is 1, delete from cache
    //else subtract 1 from cache value for that character
    for (let i = 0; i < t.length; i++) {
      if (!cache.hasOwnProperty(t[i])) return t[i]
      else if (cache.hasOwnProperty(t[i]) && cache[t[i]] === 1) {
        delete cache[t[i]]
      }
      else cache[t[i]] -= 1
    }
};

console.log(findDiff("a", "aa")); //expect a
console.log(findDiff("ae", "aea")); //expect a
console.log(findDiff("abcd", "abcde")); // expect e
console.log(findDiff("", "y")); //expect y